# Generated by Django 4.2.6 on 2023-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_rename_car_created_at_car_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='lift_due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_first',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='stairs_due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='tires_due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='end',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fcard',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fcard',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
