# Generated by Django 4.2.6 on 2023-10-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0006_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
    ]
