# Generated by Django 4.2.6 on 2023-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0008_alter_driver_end_alter_driver_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
