# Generated by Django 4.2.6 on 2023-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0009_alter_driver_end_alter_driver_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='lift_due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_first',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='stairs_due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='tires_due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fcard',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
