# Generated by Django 4.2.6 on 2023-10-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0010_alter_car_lift_due_alter_car_reg_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vl',
            field=models.ForeignKey(blank=True, max_length=8, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.vl'),
        ),
    ]
