# Generated by Django 4.2.6 on 2023-10-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0012_remove_car_fcard_lastdigits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('DR', 'Chauffør'), ('ASSIS', 'Assistent')], default='DR', max_length=15),
        ),
    ]
