# Generated by Django 4.2.6 on 2023-10-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0013_alter_driver_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fcard',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.fcard'),
        ),
        migrations.AlterField(
            model_name='car',
            name='size',
            field=models.CharField(blank=True, choices=[('SM', 'Stor'), ('MD', 'Mellem'), ('BG', 'Lille')], default='BG', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(choices=[('19', '2019'), ('20', '2020'), ('21', '2021'), ('22', '2022'), ('23', '2023'), ('24', '2024'), ('25', '2025'), ('26', '2026'), ('27', '2027'), ('28', '2028'), ('29', '2029'), ('30', '2030')], default='23', max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fcard',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TMS.fcard'),
        ),
        migrations.AlterField(
            model_name='vl',
            name='vltype',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='5', max_length=8, null=True),
        ),
    ]
