# Generated by Django 4.2.6 on 2023-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0014_alter_car_fcard_alter_car_size_alter_car_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
