# Generated by Django 4.2.6 on 2023-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0015_alter_driver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='size',
            field=models.CharField(blank=True, choices=[('Stor', 'Stor'), ('Mellem', 'Mellem'), ('Lille', 'Lille')], default='Lille', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('Chauffør', 'Chauffør'), ('Assistent', 'Assistent')], default='Chauffør', max_length=15),
        ),
    ]
