# Generated by Django 4.2.6 on 2023-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0016_alter_car_size_alter_driver_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('1', 'Chauffør'), ('2', 'Assistent')], default='1', max_length=15),
        ),
    ]
