# Generated by Django 4.2.6 on 2023-10-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0017_alter_driver_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('Chauffør', '1'), ('Assistent', '2')], default='Chauffør', max_length=15),
        ),
    ]
