# Generated by Django 4.2.6 on 2023-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0018_alter_driver_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='fromdt',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tilldt',
        ),
        migrations.AddField(
            model_name='trip',
            name='fromd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fromt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='tilld',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='tillt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('Chauffør', 'Chauffør'), ('Assistent', 'Assistent')], default='Chauffør', max_length=15),
        ),
        migrations.AlterField(
            model_name='fcard',
            name='fctype',
            field=models.CharField(blank=True, choices=[('60', '60'), ('61', '61'), ('61', '62'), ('61', '63'), ('61', '64'), ('61', '65')], default='63', max_length=5, null=True),
        ),
    ]
