# Generated by Django 4.2.6 on 2023-10-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0019_remove_trip_fromdt_remove_trip_tilldt_trip_fromd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tilld',
            field=models.DateField(blank=True, default='01/01/2023', null=True),
        ),
    ]
