# Generated by Django 4.2.6 on 2023-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0020_alter_trip_tilld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tilld',
            field=models.DateField(blank=True, null=True),
        ),
    ]
