# Generated by Django 4.2.6 on 2023-10-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0021_alter_trip_tilld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='p_type',
            field=models.CharField(blank=True, choices=[('Pro%', 'Pro%'), ('Tid', 'Tid')], default='Pro%', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pause',
            field=models.DurationField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='percent',
            field=models.IntegerField(blank=True, choices=[('48%', '48%'), ('49%', '49%'), ('50%', '50%'), ('51%', '51%'), ('52%', '52%'), ('53%', '53%'), ('54%', '54%'), ('55%', '55%')], default='48%', null=True),
        ),
    ]
