# Generated by Django 4.2.6 on 2023-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0022_alter_trip_p_type_alter_trip_pause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='p_type',
            field=models.CharField(blank=True, choices=[('Pro%', 'Pro%'), ('Tid', 'Tid')], default='Pro%', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='percent',
            field=models.CharField(blank=True, choices=[('48%', '48%'), ('49%', '49%'), ('50%', '50%'), ('51%', '51%'), ('52%', '52%'), ('53%', '53%'), ('54%', '54%'), ('55%', '55%')], default='48%', max_length=5, null=True),
        ),
    ]
