# Generated by Django 4.2.6 on 2023-10-13 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0023_alter_trip_p_type_alter_trip_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='work_time',
        ),
        migrations.AlterField(
            model_name='trip',
            name='fromd',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fromt',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tilld',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tillt',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
