# Generated by Django 4.2.6 on 2023-10-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0024_remove_trip_work_time_alter_trip_fromd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='work_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
