# Generated by Django 4.2.6 on 2023-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0025_trip_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fromd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='per_total',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='percent',
            field=models.DecimalField(blank=True, choices=[(48.0, 48.0), (49.0, 49.0), (50.0, 50.0), (51.0, 51.0), (52.0, 52.0), (53.0, 53.0), (54.0, 54.0), (55.0, 55.0)], decimal_places=2, default=48.0, max_digits=6, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tilld',
            field=models.DateField(blank=True, null=True),
        ),
    ]
