# Generated by Django 4.2.6 on 2023-10-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0026_alter_trip_fromd_alter_trip_per_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='percent',
            field=models.DecimalField(blank=True, choices=[('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55')], decimal_places=2, default='48', max_digits=6, max_length=5, null=True),
        ),
    ]
