# Generated by Django 4.2.6 on 2023-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0027_alter_trip_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='per_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='percent',
            field=models.IntegerField(blank=True, choices=[('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55')], default='48', null=True),
        ),
    ]
